[package]
name = "ferrofetch"
version = "1.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/Kiwilus/ferrofetch.git"
keywords = ["system-info", "cli", "system_tool"]
categories = ["command-line-utilities"]

[dependencies]
owo-colors = "4.3.0"
os_info = "3.15.0"
whoami = "2.1.2"
clap = { version = "4", features = ["derive"] }
toml = "1.1.2"
serde = { version = "1", features = ["derive"] }
dirs = "6.0.0"
local-ip-address = "0.6.13"
gfxinfo = { version = "0.1.2", features = ["gpu_info"] }
sysinfo = "0.39.5"

[[bin]]
name = "ferrofetch"
path = "src/main.rs"
